### ISSUE TITLE
string with just comments causes error

### ISSUE THREAD

**Issue by tmccombs** [pnathan/pp-toml#15]
If you run `parse-toml` on a string containgin only comments you get a SIMPLE-ESRAP-ERROR complaining a bout an incomplete parse:

```
At

  
  
  ^ (Line 1, Column 0, Position 0)

Incomplete parse.
   [Condition of type ESRAP::SIMPLE-ESRAP-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1003B90003}>)

Backtrace:
  0: (ESRAP::SIMPLE-ESRAP-ERROR " ..)
  1: (ESRAP::PROCESS-PARSE-RESULT #S(ESRAP::RESULT :%PRODUCTION ((NIL NIL)) :POSITION 0) " ..)
  2: (PARSE-STRING " ..)
  3: (PARSE-TOML "#foo ..)
```

**Comment by pnathan** [comment]
what is the appropriate behaviour here?

**Comment by tmccombs** [comment]
The behaviour for a string containing only comments and/or whitespace should be the same as for an empty string i.e. an empty hash-table.

**Comment by pnathan** [comment]
Sorry about that, I should know better to drink coffee before responding to issues.
