### ISSUE TITLE
ecl compilation failure: "FORM" is an illegal character name

### ISSUE THREAD

**Issue by kat-co** [pnathan/pp-toml#20]
https://github.com/pnathan/pp-toml/blob/5a65c1855b15ddf370d140f7cd75f5a9dbae40c3/pp-toml.lisp#L101-L102

**Comment by kat-co** [comment]
I don't really know. I use [guix](https://guix.gnu.org)'s [package](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/lisp.scm?h=master#n226). That probably looks pretty busy, but most of it is modifying the installed path to meet Guix's reproducibility guarantees and unique path layout. Otherwise it looks pretty straightforward? If you're interested, you can run Guix as a package manger on any distro.

Also, I actually don't use ecl, but I do [derive](https://github.com/kat-co/guix-channels/blob/upstream-staging/upstream/packages/lisp-xyz.scm#L159-L160) Guix ecl packages from the SBCL counterparts for the greater good. I've tried it recently and everything went just fine.

I hope that helps!

**Comment by kat-co** [comment]
I can confirm that #21 fixes this issue. Thank you very much!

**Comment by kat-co** [comment]
Ping!

**Comment by pnathan** [comment]
@kat-co apologies.

**Comment by kat-co** [comment]
No apologies needed; life gets busy! Thanks for the fix!
