### ISSUE TITLE
Fails to build on CCL due to the \#From character

### ISSUE THREAD

**Issue by avodonosov** [pnathan/pp-toml#25]
Thus breaking dependent systems as well:
https://github.com/fisxoj/coo/issues/26

**Comment by avodonosov** [comment]
May be better to invert the reader conditional at https://github.com/pnathan/pp-toml/blob/a62825be8fb1f27760585ae138c904c8029b34db/pp-toml.lisp#L102, so that only implementations known to work are included, instead of excluding the implementations known to not work.

**Comment by pnathan** [comment]
Hi @avodonosov - good to know.  Thank you for the bug report.

I'll see about addressing this in the next 1-2 days.

**Comment by avodonosov** [comment]
@pnathan , the above pull request fixes the issue by programmatically determining whether the current lisp implementation supports the `#\From` character

**Comment by pnathan** [comment]
thanks for the PR. I apologize for the ridiculous delay, I have been pretty wrapped in my (golang) work.
